### ISSUE TITLE
Not working on Raspberry Pi 4

### ISSUE THREAD

**Issue by idoodler** [kmpm/rpi-usb-gadget#1]
I recently used your script on a Raspberry Pi 4 so I can use the Pi with my iPad Pro.

The Script executed without any issue, but I don't see the interface. Neither on my mac, nor on my iPad. I already tried different cables. When I execute `ifconfig` on the pi I can see the `usb0` interface.

Are there any debugging possibilities or known issues?

**Comment by kmpm** [comment]
I don't know of any issues but 
a) it's bee a lot of updates to raspbian since I last ran the script
b) I have never tried to connect using a mac or ipad.
As for debugging, I would have a look at dmesg on the pi. Also checking any activity by dnsmasq to see if it tries to serve any DHCP requests.

I will test the script an a freshly installed PI later but I do not have access to either iPad or Mac to easily test that.

**Comment by idoodler** [comment]
I aleeady had it working without your script a long time ago using the original steps with the same cables

**Comment by kmpm** [comment]
It looks as if there is some kind of issue here. The network interface works when connecting to a Windows PC but it (windows) does complain about some USB-device not working (and from the timing it looks to be rpi) for a second or two while usb0 initializes.
But in the end I get a 10.55.0.2 IP address in windows and I can connect to 10.55.0.1 (the pi) without any issues.
This is tested on a fresh, updated RaspiOS Lite.

If you could point me to whatever you consider to be "original steps" I'll be more than happy.

**Comment by idoodler** [comment]
With "original steps" I mean the post from [here](https://www.hardill.me.uk/wordpress/2019/11/02/pi4-usb-c-gadget/). I did this over a year ago I think.

**Comment by kmpm** [comment]
Ok... this script configures the network interface as a Microsoft RNDIS one, not as ECM as in the example you gave.
I'll try to see if I can make an option to use one or the other.

**Comment by kmpm** [comment]
If you could try the version in the 'change' branch instead.
https://raw.githubusercontent.com/kmpm/rpi-usb-gadget/change/rpi4-usb.sh
It will only work on a fresh install (it fails if you used the old script).

There you will be asked if you want RNDIS or ECM device type. Please test ECM if it works better. That one should more as the one you linked to. I can not get it to work with ECM when connecting to a Windows PC though and I do not have a Linux machine with me at the moment so I have to way of verifying it.

**Comment by kmpm** [comment]
Tested the 'change' branch with openSuSE tumbleweed with 5.12 kernel and both RNDIS and ECM works together.

**Comment by idoodler** [comment]
Your updated script did not work for me. I followed the [blog post](https://www.hardill.me.uk/wordpress/2019/11/02/pi4-usb-c-gadget/) from earlier and this worked. I don't know why tho

**Comment by kmpm** [comment]
Thanks for the report and then information from your trials.
