### ISSUE TITLE
Network device type selection not working

### ISSUE THREAD

**Issue by madifz** [kmpm/rpi-usb-gadget#4]
# Steps to reproduce

- Run rpi4-usb.sh script
- Inputting 2 at the end to configure ECM network device type

### Expected behavior

Inputting 2 when selecting network device type should configure "net-ecm".

### Actual behavior

Inputting 2 configures "net-rndis".

### Proposed solution
Correcting rpi4-usb.sh line 253 DEVICeTYPE to DEVICETYPE. I made a [pull request #3](https://github.com/kmpm/rpi-usb-gadget/pull/3) to fix this. Testing locally on my machine reproduced issue and after fix "net-ecm" can be configured correctly.

P.S: Thanks for building this script, really helps alot especially as this is my first time playing around with Raspberry Pi :)

**Comment by kmpm** [comment]
Fixed with #3
