### ISSUE TITLE
Don't use fixed MAS addresses

### ISSUE THREAD

**Issue by thagrol** [kmpm/rpi-usb-gadget#5]
Lines 150 and 151 use fixed values for the host and device MAC addresses. This will cause a conflict if two Pi configured by this script are connected to the same USB host.

It would be better to derive MAC addresses from the Pi's serial number and to use the locally administered range as explained here: https://github.com/thagrol/Guides

**Comment by thagrol** [comment]
See also line 129

**Comment by MystPi** [comment]
How could I edit the script to do this myself?

**Comment by thagrol** [comment]
If you look in the repository I linked to above youll find a script that does just that. It only sets up the ethernet gadget via configfs and not any of the other stuff your script does though.

Mainly because the other stuff isn't always needed.

Oh, and slightly off topic, you might want to prompt for an IP address range too. Having multiple DNS servers and clients in the same IP address range will also be problematic if more than one PI is configured with this script and connected to teh same USB host at the same time. In fact, from skimming that script you'll probably end up with all the gadget Pi having the same IP address. as things stand.

If you're starting to think things are complicated, you'd be right.

**Comment by MystPi** [comment]
> If you look in the repository I linked to above youll find a script that does just that. It only sets up the ethernet gadget via configfs and not any of the other stuff your script does though.

Thank you. Just so you know, I am not the owner of this repo; @kmpm is.

**Comment by kmpm** [comment]
Thanks @MystPi, will try to fix this the upcoming weekend.
