### ISSUE TITLE
Sourcing power from the computer?

### ISSUE THREAD

**Issue by danergo** [kmpm/rpi-usb-gadget#7]
Let me ask a straightforward easy question.

Can we use RPi4 as USB gadget *without* providing it power separately?

I.e. I wish to use RPi4 as USB gadget, but I don't have power sockets around. If I plug it into my computer as USB OTG, can it function as an USB gadget? Like a mass storage?

Thank you

**Comment by TheFloydman** [comment]
Only if the port is able to supply enough power (3A for a RPi4). Otherwise you will need to power it separately through the GPIO pins (you can even use the official Raspberry Pi PoE HAT for that).

**Comment by kmpm** [comment]
I have used a Rpi4 on several "ordinary" computers without issues.
It won't draw 3A all the time. So for simpler, less demanding, tasks it usually works fine.
