### ISSUE TITLE
 /boot/config.txt is now moved to /boot/firmware/config/txt

### ISSUE THREAD

**Issue by gmanturtle72** [kmpm/rpi-usb-gadget#8]
One command executed adds the line "dtoverlay=dwc2" to /boot/config.txt. however, as of recent updates, the conifg file needed to be changed is moved to the directory /boot/firmware/config.txt. adding  "dtoverlay=dwc2" to this config file enables the pi to work as a usbc gadget after running this script.

**Comment by kmpm** [comment]
thanks for reporting: I will have to figure out a way of detecting either this or what os version that is used.
